package org.springframework.boot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Validates that the JDK 11 → 17+ migration was applied correctly.
 *
 * <p>These tests are auto-generated by the auto-remediation system and are
 * intentionally simple: they verify (a) the JVM version at runtime is Java 17+
 * and (b) post-Java-11 language features compile and behave correctly.
 *
 * <p>Feel free to expand them with project-specific migration checks.
 */
class AutoRemediationMigrationTest {

    /** Java 16+ record — fails to compile on Java 11 source level. */
    record MigrationMarker(int javaVersion, String status) {}

    @Test
    void javaVersionIsAtLeast17() {
        int feature = Runtime.version().feature();
        assertTrue(
            feature >= 17,
            "Expected JVM 17+, but running on Java " + feature + ". "
                + "Check that the build and runtime images were updated to Java 17+."
        );
    }

    @Test
    void java16RecordCompiles() {
        // Records were finalised in Java 16.  If this compiles and runs,
        // the compiler target has been raised beyond 11.
        var marker = new MigrationMarker(17, "migrated");
        assertEquals(17, marker.javaVersion());
        assertEquals("migrated", marker.status());
    }

    @Test
    void patternMatchingInstanceofWorks() {
        // Pattern matching for instanceof was finalised in Java 16 (JEP 394).
        Object value = Integer.valueOf(42);
        String result;
        if (value instanceof Integer i && i > 0) {
            result = "positive int: " + i;
        } else if (value instanceof Integer i) {
            result = "non-positive int: " + i;
        } else if (value instanceof String s) {
            result = "string: " + s;
        } else {
            result = "other";
        }
        assertEquals("positive int: 42", result);
    }
}